[package]
name = "pod2"
version = "0.1.0"
authors = ["Davide Mor <tazdevil971@gmail.com>"]
edition = "2018"

[dependencies]
pod2-macro = { path = "./pod2-macro" }

[workspace]
members = [
    "pod2-macro",
    ".",
]